modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
modId="kiln"
version="0.1"
displayName="kiln"
description="funky kiln block smelt ya clay"

[[dependencies.kiln]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.kiln]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
