modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="kilnmod"
version="${file.jarVersion}"
displayName="Kiln: A mod!"
description="The Funky kiln Block smelt Ya clay"

[[dependencies.kilnmod]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.kilnmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
