modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="kilnmod"
version="${file.jarVersion}"
displayName="Kiln: A mod!"
description="The Funky kiln Block smelt Ya clay"

[[dependencies.kiln]]
    modId="forge"
    mandatory=true
    versionRange="[36.1.32,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.kiln]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
